### ISSUE TITLE
How to unescaped PrettyJson output?

### ISSUE THREAD

**Issue by wakawaka54** [matiboy/angular2-prettyjson#20]
I am using this module like this:

`
  entryComponents: [
    PrettyJsonComponent],
 imports: [
       PrettyJsonModule]
`

`
<prettyjson [obj]="execution"></prettyjson>
`

I am getting a JSON output with escaped quotes for JSON strings. While this is accurate, it isn't very pretty.

ie:
`
      "WorkflowMetadata": [
        "{\"id\":\"597f805b55e1c063006f97e3\",\"identifier\":{\"id\":\"WorkflowMetadata\"},\"index\":0}",
        "{\"id\":\"5980ac79e76f8ab48b485b41\",\"identifier\":{\"id\":\"WorkflowMetadata\"},\"index\":1}"
      ],
`

Is there a simple way to configure this out?

Thank you!

**Comment by matiboy** [comment]
Hi @wakawaka54 
Thanks for opening this issue.

Since the data inside WorkflowMetadata is already strings, the output will escape quotes; I can't think of a way around it.

A solution would therefore need to be at your data level where you'd parse each item in WorkflowMetadata (either to a new property of the component or overriding WorkflowMetadata)
Maybe using a Rx observable with `.map(WFMD => WFMD.map(item => JSON.parse(item))`
and then piping `execution` through the `async` pipe `[obj]="execution$ | async"

Sorry I can't be of more help on this

Mat
